all: main.cpp Reseaux.cpp Noeuds.cpp Liens.cpp Molecules.cpp Atomes.cpp Liaisons.cpp Graphes.cpp Aretes.cpp Sommets.cpp
	g++ -std=c++11 -o main main.cpp Reseaux.cpp Noeuds.cpp Liens.cpp Molecules.cpp Atomes.cpp Liaisons.cpp Graphes.cpp Aretes.cpp Sommets.cpp -fpermissive
